# Generated by Django 5.1.2 on 2024-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('equity', 'Equity'), ('tuition_assistance', 'Tuition Assistance'), ('dental', 'Dental Insurance'), ('medical', 'Medical Insurance'), ('car', 'Car'), ('pension', 'Pension Contribution'), ('paid_leave', 'Paid Leave')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('young_team', 'Young Team'), ('open_office', 'Open Office'), ('work_from_home', 'Work from Home'), ('flexible_hours', 'Flexible Hours'), ('pet_friendly', 'Pet Friendly'), ('gym_on_site', 'Gym On Site'), ('free_snacks', 'Free Snacks'), ('team_outings', 'Team Outings')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(choices=[('new_grad', 'New Grad'), ('intermediate', 'Intermediate'), ('senior', 'Senior')], default='new_grad', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='travel_required',
            field=models.CharField(choices=[('none', 'None'), ('some', 'Some'), ('frequent', 'Frequent')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='work_type',
            field=models.CharField(choices=[('on_site', 'On Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='benefits',
            field=models.ManyToManyField(to='board.benefit'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='flairs',
            field=models.ManyToManyField(to='board.flair'),
        ),
    ]
