# Generated by Django 5.1.2 on 2024-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_status',
            field=models.CharField(blank=True, choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter')], max_length=20, null=True),
        ),
    ]
