# Generated by Django 5.1.2 on 2024-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_language_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
